### ISSUE TITLE
Ne radi login

### ISSUE THREAD

**Issue by ToniMilicevic** [SoftverInzenjeringETFSA/SI2014Tim10#32]
Komponenta:
glavna_knjiga login

commit ID:
6dc18d7d720238b62414f4829f99b8df97087117

Opis problema:
Ne pristupa se korisnickom racunu iako su uneseni valdini podaci.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Glavna knjiga FAMEHOF".
2. Izabrati opciju Administraor u dropdown meniju.
3. U polje "Korisnicko ime" unijeti "tms1337".
4. U polje "Lozinka" unijeti "44253432".
5. Kliknuti na dugme "Uloguj se!".

Dobijeni rezultat:
- Aplikacija ostane na istoj login formi.

Očekivani rezultat:
- Očekuje se da se udje na panel za administratora.

Opis problema:
Ne pristupa se korisnickom racunu administratora iako su uneseni validni podaci.
![image](https://cloud.githubusercontent.com/assets/11351691/7813766/ed9c71c0-03bd-11e5-8bba-cb5c16a99fc2.png)

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Glavna knjiga FAMEHOF".
2. Izabrati opciju Administraor u dropdown meniju.
3. U polje "Prvi sabirak" unijeti "tms1337".
4. U polje "Drugi sabirak" unijeti "44253432".
5. Kliknuti na dugme "Uloguj se!".

Dobijeni rezultat:
- Aplikacija ostane na istoj login formi.

Očekivani rezultat:
- Očekuje se da se udje na panel za administratora.

**Comment by spahicharis** [comment]
hahaha , cuj sabirak
