### ISSUE TITLE
Nema unit testova ni za jednu od klasa

### ISSUE THREAD

**Issue by eminamuharemovic** [SoftverInzenjeringETFSA/SI2014Tim10#35]
Komponenta:
glavnja-knjiga

commit ID:
f6cfbc465175f1a7332fd9b3ea8c8f0c67f35c54

Opis problema:
Ne postoje unit testovi ni za jednu od klasa, odnosno postoji samo jedan unit test (HibernateSessionManagerTest)

Koraci za reproduciranje problema:
1. Pokrenuti unit testove

Dobijeni rezultat:
- Pokrene se samo jedan postojeci test

Očekivani rezultat:
- Trebali bi postojati testovi i za ostale klase

**Comment by mnuhodzic** [comment]
ispravljeno u ovom komitu 4347cc5
