### ISSUE TITLE
Greska u validiranju broja telefona

### ISSUE THREAD

**Issue by eminamuharemovic** [SoftverInzenjeringETFSA/SI2014Tim10#47]
Komponenta:
glavna-knjiga desktop aplikacija

commit ID:
f6cfbc4

Opis problema:
Pri unosu validnog broja telefona (naprimjer 0601233211 koji ima 10 cifara) forma za unos novog korisnika izbaci poruku da broj nije validan. Također, istu grešku dobijem i za brojeve tipa +387601233211.

Koraci za reproduciranje problema:
1. Pokrenuti HomeFrameAdmin formu 
2. Klik na dugme za dodavanje novog korisnika
3. Unijeti validne podatke i broj telefona 0601233211
4. Klik na unos korisnika

Dobijeni rezultat:

Pojavi se poruka da broj telefona nije validan.

Očekivani rezultat:

S tim da je 0601233211 validan broj, korisnik bi se trebao uspješno snimiti u bazu podataka.

**Comment by ezugor1** [comment]
Greska je vrlo slična prethodnoj, ako je pogrešno validirana jedna forma, trebalo se to sve pod jedan issue staviti, prethodni se naravno prepravio
