### ISSUE TITLE
Bug 15

### ISSUE THREAD

**Issue by ToniMilicevic** [SoftverInzenjeringETFSA/SI2014Tim10#48]
Komponenta:
glavna-knjiga

commit ID:
5944555d9e9140ee2eb32ccf532bf165a1278e03

Opis problema:
Ne prikazuju se korisnici kada se otvori padajuca lista na editovanju korisnika u admin dijelu.

Koraci za reproduciranje problema:
1. Pokrenuti EditujKorisnikaFrame.java formu 
2. Kliknuti na padajucu listu JMBG korisnika kojeg zelim promjeniti.

Dobijeni rezultat:
Prazni su redovi u padajucoj listi, iako se nalaze odredjeni korisnici u bazi.

Očekivani rezultat:
Potrebno je da se ispisu JMBG korisnika iz baze.

**Comment by farisodobasic** [comment]
Nemoguce je pokrenuti samo navedenu formu bez da se ne prodje proces prijave korisnika, jer onda nece povuci podatke iz baze
