### ISSUE TITLE
Forma za izmjenu kontnog plana se otvara bez prethodnog odabira koji kontni plan se zeli izmjeniti

### ISSUE THREAD

**Issue by sumejabotulja** [SoftverInzenjeringETFSA/SI2014Tim10#55]
Komponenta:
glavna_knjiga

commit ID:
0199e67

Opis problema:
Na formi kontnog plana kada se odabere button izmjena kontnog plana otvara se forma za izmjenu, bez prethodnog odabira koji kontni plan se zeli izmjeniti.

Koraci za reproduciranje problema:
1. Prijaviti se kao racunovodja.
2. Izabrati opciju Konto opcije u meniju.
3. Odabrati Kontni plan.
4. Odabrati button "Izmjeni kontni plan".
5. Otvara se forma za izmjenu kontnih planova

Dobijeni rezultat:
Iako nije odabran niti jedan kontni plan, nisi tu podaci uneseni u polja za pretragu, forma za izmjenu se otvara. Sto se vidi na sljedecoj slici: http://prntscr.com/79w4os

Očekivani rezultat:
Ispis poruke da se odabere neki kontni plan koji se zeli izmjeniti ili onemoguciti button za izmjenu dok se ne odabere kontni plan sa forme.

**Comment by farisodobasic** [comment]
Svako preduzece ima JEDAN kontni plan koji se kreira na osnovu kontnog okvira, gde se biraju konta iz navedenog kontnog okvira.
