### ISSUE TITLE
Kada se prijavim kao administrator sistem ne otvara korisnički interfejs za administratora

### ISSUE THREAD

**Issue by eminamuharemovic** [SoftverInzenjeringETFSA/SI2014Tim10#59]
Komponenta:
glavna-knjiga desktop aplikacija

commit ID:
f6cfbc4

Opis problema:
Kada se prijavim kao administrator sistem ne otvara korisnički interfejs za administratora kako je opisano u SRS-u.

Koraci za reproduciranje problema:
1. Pokrenuti LoginFrame formu
3. Unijeti validno korisničko ime, lozinku, tip korisnika
4. Klik na dugme Uloguj se

Dobijeni rezultat:

http://prntscr.com/7aor2q

Očekivani rezultat:

Trebao bi se otvoriti korisnički interfejs za administratora kako je opisano u SRS-u:
http://prntscr.com/7aov0x

**Comment by tms1337** [comment]
nije valjana situacija u bazi, jmbg atribut bude 0 i zato se desi bug. 
nacin ispravke je da se u bazi populateju polja za koje se pretpostavlja da nisu null.

**Comment by mnuhodzic** [comment]
Dupli issue, kolega ga je vec prijavio #32
