### ISSUE TITLE
Nedovoljan opis greške koja se javlja pri pokušaju spašavanja novog naloga

### ISSUE THREAD

**Issue by AdnaDurakovic** [SoftverInzenjeringETFSA/SI2014Tim10#66]
Komponenta:
Nalog

commit ID:
3c3eaa2

Opis problema:
Nedovoljan opis greške koja se javlja pri pokušaju spašavanja novog naloga

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame” te se ulogovati kao računovođa koristeći zadane podatke (username: “nejrich”, password: “bilosta”).
2. Izabrati opciju "Nalog opcije” u glavnom meniju.
3. U podmeniju odabrati opciju “Kreiraj novi nalog”.
4. U polja “Naziv” i “Šifra naloga” unijeti podatke.
5. Kliknuti na button “Spasi nalog”.

Dobijeni rezultat:
- Iskače prozor koji kaže da se desila greška prilikom spašavanja naloga, ali klijent ne može znati gdje je tačno napravio grešku na osnovu ove informacije.
  (http://pokit.org/get/?a0a362ea9b7f5c2f47822b8aae09af0b.jpg)

Očekivani rezultat:
- Očekuje se ispis podataka o greškama koje su se desile, dakle detaljno i konkretno objašnjenje grešaka i mjesta na kojima su se greške pojavile.

**Comment by mnuhodzic** [comment]
prijavljen vec ovaj issue #42
