### ISSUE TITLE
Nedovoljan opis greške koja se javlja pri pokušaju brisanja naloga

### ISSUE THREAD

**Issue by AdnaDurakovic** [SoftverInzenjeringETFSA/SI2014Tim10#67]
Komponenta:
Nalog

commit ID:
3c3eaa2

Opis problema:
Nedovoljan opis greške koja se javlja pri pokušaju brisanja naloga

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame” te se ulogovati kao računovođa koristeći zadane podatke (username: “nejrich”, password: “bilosta”).
2. Izabrati opciju "Nalog opcije” u glavnom meniju.
3. U podmeniju odabrati opciju “Kreiraj novi nalog”.
4. Kliknuti na button “Obriši nalog”.

Dobijeni rezultat:
- Iskače prozor koji kaže da se desila greška prilikom brisanja naloga, ali klijent ne može znati gdje je tačno napravio grešku na osnovu ove informacije.
  (http://pokit.org/get/?715eb35ed7b1e7720677242a5aa01eb7.jpg)

Očekivani rezultat:
- Očekuje se ispis podataka o greškama koje su se desile, dakle detaljno i konkretno objašnjenje grešaka i mjesta na kojima su se greške pojavile.

**Comment by mnuhodzic** [comment]
ponovo dupli issue #58
