### ISSUE TITLE
Nedovoljan opis greške koja se javlja pri pokušaju upisa naloga

### ISSUE THREAD

**Issue by AdnaDurakovic** [SoftverInzenjeringETFSA/SI2014Tim10#68]
Komponenta:
Nalog

commit ID:
3c3eaa2

Opis problema:
Nedovoljan opis greške koja se javlja pri pokušaju upisa naloga.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame” te se ulogovati kao računovođa koristeći zadane podatke (username: “nejrich”, password: “bilosta”).
2. Izabrati opciju "Nalog opcije” u glavnom meniju.
3. U podmeniju odabrati opciju “Kreiraj novi nalog”.
4. Kliknuti na button “Dodaj stavku”.
5. Dodati stavku sa željenim parametrima.
6. Odabrati dodanu stavku u tableli, te kliknuti na button “Upiši nalog”.

Dobijeni rezultat:
- Iskače prozor koji kaže da se desila greška prilikom zaključivanja naloga, ali klijent ne može znati gdje je tačno napravio grešku na osnovu ove informacije.
  (http://pokit.org/get/?e5856a13a8178ba6b58cdd545c31723c.jpg)

Očekivani rezultat:
- Očekuje se ispis podataka o greškama koje su se desile, dakle detaljno i konkretno objašnjenje grešaka i mjesta na kojima su se greške pojavile, kako bi klijent znao šta da ispravi.

**Comment by mnuhodzic** [comment]
prijavljen ovaj issue #57
