### ISSUE TITLE
Aplikacija se zaledi kada se pokuša otvoriti “Pregled naloga” 

### ISSUE THREAD

**Issue by AdnaDurakovic** [SoftverInzenjeringETFSA/SI2014Tim10#69]
Komponenta:
PregledNaloga

commit ID:
3c3eaa2

Opis problema:
Aplikacija se zaledi kada se pokuša otvoriti “Pregled naloga” 

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame” te se ulogovati kao računovođa koristeći zadane podatke (username: “nejrich”, password: “bilosta”).
2. Izabrati opciju "Nalog opcije” u glavnom meniju.
3. U podmeniju odabrati opciju “Pregled naloga”.

Dobijeni rezultat:
- Aplikacija je zaleđena, te nema drugog izlaza osim da se klikne “End Task” u “Task Manager”-u.

Očekivani rezultat:
- Očekuje se otvaranje forme za pregled naloga.

**Comment by tms1337** [comment]
nemoguce reproducirati
