### ISSUE TITLE
Nije usaglašeno korištenje afrikata u aplikaciji

### ISSUE THREAD

**Issue by AdnaDurakovic** [SoftverInzenjeringETFSA/SI2014Tim10#70]
Komponenta:
HomeFrameRacunovodja, KontniPlanFrame, KontniOkvirFrame 

commit ID:
3c3eaa2

Opis problema:
Nije usaglašeno korištenje afrikata u aplikaciji.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame” te se ulogovati kao računovođa koristeći zadane podatke (username: “nejrich”, password: “bilosta”).
2. Izabrati opciju "Konto opcije” u glavnom meniju.
3. U podmeniju odabrati opciju “Kontni okvir”.
4. U podmeniju odabrati opciju “Kontni plan”.

Dobijeni rezultat:
- Na nekim formama se koriste afrikati u pisanju naziva, dok se na nekim drugim formama ne koriste.
  Primjer korištenja afrikata:
  (http://pokit.org/get/?3b93768087d3e56e45830a4f55b7d8e7.jpg)
  Primjer ne korištenja afrikata:
  (http://pokit.org/get/?0f910e05d1dc61512654febecb45a96b.jpg)

Očekivani rezultat:
- Očekuje se da je aplikacija konzistentna što se tiče jezika i šablona koji se koriste prilikom imenovanja.

**Comment by mnuhodzic** [comment]
ovo nije greska
