### ISSUE TITLE
Nije onemogućen rad na parent frameu u toku rada sa child frameom

### ISSUE THREAD

**Issue by AdnaDurakovic** [SoftverInzenjeringETFSA/SI2014Tim10#71]
Komponenta:
KontniPlanFrame

commit ID:
3c3eaa2

Opis problema:
Parent frame, u ovom slučaju “KontniPlanFrame”, nije onemogućen kada se otvori njegov child frame “KontniPlanIzmjenaFrame”. 

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame” te se ulogovati kao računovođa koristeći zadane podatke (username: “nejrich”, password: “bilosta”).
2. Izabrati opciju "Konto opcije” u glavnom meniju.
3. U podmeniju odabrati opciju “Kontni plan”.
4. Kliknuti više puta na button “Izmijeni kontni plan”.

Dobijeni rezultat:
- Otvara se više child frame-ova, tj. “KontniPlanIzmjenaFrame”-ova.
  (http://pokit.org/get/?8a9e8e7c08c12146a74a0a699e9565c6.jpg)

Očekivani rezultat:
- Očekuje se da se onemogući rad na “KontniPlanFrame”-u sve dok se ne prekine rad sa “KontniPlanIzmjenaFrame”-om.

**Comment by tms1337** [comment]
privremeno invalid dok razmotrimo da li je bug hehe

**Comment by AdnaDurakovic** [comment]
Jeste li razmotrili?
