### ISSUE TITLE
Opcija u glavnom meniju “Help” nema definisanu funkcionalnost

### ISSUE THREAD

**Issue by AdnaDurakovic** [SoftverInzenjeringETFSA/SI2014Tim10#72]
Komponenta:
HomeFrameRacunovodja

commit ID:
3c3eaa2

Opis problema:
Opcija u glavnom meniju “Help” nema definisanu funkcionalnost. 

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame” te se ulogovati kao računovođa koristeći zadane podatke (username: “nejrich”, password: “bilosta”).
2. Izabrati opciju "Help” u glavnom meniju.

Dobijeni rezultat:
- Ne dešava se ništa prilikom klika na “Help” opciju glavnog menija.
  (http://pokit.org/get/?11af3118136a10d0880b791efe5b2304.jpg)

Očekivani rezultat:
- Očekuje se otvaranje forme ili neka druga akcija koja je predviđena ukoliko se odabere opcija “Help”.

**Comment by mnuhodzic** [comment]
Ponovo duplikat #40
