### ISSUE TITLE
Edituj korisnika validacija polja

### ISSUE THREAD

**Issue by ToniMilicevic** [SoftverInzenjeringETFSA/SI2014Tim10#76]
Komponenta:
EditujKorisnikaFrame

commit ID:
ff712a0

Opis problema:
Datum nije validiran, moguce unijeti datum u buducnosti.
Broj licne karte nije validiran, potrebno je regulirati duzinu unesenih podataka i znakove koji se smiju unijeti .
Mail se moze unijeti u najrazlicitijem formatu, jer nije validirano.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame” te se ulogovati kao administrator
2. Izabrati opciju u administratorskom dijelu "Edituj klijenta"
3. Unijeti datum u buducnosti.
4. Za broj licne karte unijeti 43432//_TTTTR.
5. Pod mailom unijeti abraka@sf/_/dssd@okopPA.SA.

Dobijeni rezultat:
Uspjesno dodavanje korisnika.

Očekivani rezultat:
Ocekuje se da sistem prikaze poruku koja bi uputila korisnika da se validiraju ovi podaci.

**Comment by ezugor1** [comment]
Možda je do mene, ali ja ovdje uopšte ne vidim polje za unos broja lične karte, niti unos datuma. Naravno mail je validiran
